### ISSUE TITLE
plans to create public instance, similar to builds.sr.ht?

### ISSUE THREAD

**Issue by kanishka-work** [ocurrent/ocurrent#249]
Are there plans to provide a hosted instance of this, similar to https://man.sr.ht/builds.sr.ht/ ?

**Comment by dra27** [comment]
OCurrent is a library for writing processing pipelines, so if by a hosted instance of "this" you mean a place to run arbitrary OCurrent pipelines, the answer is no 🙂 However...

[ocurrent/overview](https://github.com/ocurrent/overview) describes the various public deployments we presently have - in particular, [ocurrent/opam-repo-ci](https://github.com/ocurrent/opam-repo-ci) runs tests for all pull requests to [opam's public repository](https://github.com/ocaml/opam-repository) and [ocurrent/ocaml-ci](https://github.com/ocurrent/ocaml-ci) provides CI for [a range of OCaml projects](https://ci.ocamllabs.io/github). We're still working both on features of ocaml-ci and also on Windows and macOS support for the cluster, which is why at present our instance of ocaml-ci is not open to all repositories (we haven't yet decided whether to open it up more once the platform support is ready).

Everything we're running at the moment is a deployment of the those various repositories, so everything should be there to to replicate it (and if it's not, issues or pull requests are warmly welcomed!). In particular, you do not need a "cluster" of machines - one's local machine is sufficient to have a go.
