### ISSUE TITLE
`Process.check_output` uses an atomic read to get the entirety of stdout

### ISSUE THREAD

**Issue by shonfeder** [ocurrent/ocurrent#449]
Currently we use an unqualified `Lwt_io.read` to get the stdout of a subprocess:

https://github.com/ocurrent/ocurrent/blob/ca5976f4cf226e3fc278d1149f7c295e174acaa9/lib/process.ml#L161

IIUC, since this doesn't set a `count` limit (as we do, e.g., in 

https://github.com/ocurrent/ocurrent/blob/ca5976f4cf226e3fc278d1149f7c295e174acaa9/lib/process.ml#L113-L119

) this read will be blocking until the entire output is consumed (see https://github.com/ocsigen/lwt/blob/48abed72467ca7479e95f1be06d02f40c7c434bd/src/unix/lwt_io.ml#L1207-L1208).

On large outputs, I expect this could be a drag, and it would be nicer to yield periodically.

I noticed this while reading the process functions while plotting a fix for https://github.com/ocurrent/docker-base-images/issues/211

**Comment by talex5** [comment]
`copy_to_log` reads whatever is available in chunks because:
1. It needs to write them to the log as soon as they're available so you can see the output before the job has finished, and
2. It doesn't need to keep the whole log in memory at once.

This doesn't apply to `check_output`, which returns all the output as a single in-memory string and only when the function has finished.

**Comment by shonfeder** [comment]
Thanks, @talex5 :)  That difference in use cases was pretty clear to me. My thought that this may be sub-optimal was based on assumptions about the value of yielding periodically when reading long input, not about concerns over memory overhead or streaming out data. But I did some "experiments" and read deeper today, and see that my assumptions were wrong, and based on a faulty model of the how Lwt would be scheduling tasks.

Sorry for the noise and thanks for offering the clarification!
