### ISSUE TITLE
Make Camelus an ocurrent process

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/ocurrent#45]
I'm not sure where to post this exactly so I'll post this here for now.

In the effort of making a new CI the idea came up to make https://github.com/AltGr/Camelus/ an integrated part of it (as a module). In theory this should need only a bit of rewiring of the connexion with github but I'm not sure of the details, @talex5 might have a better idea.

cc @AltGr @ThomasBlanc @avsm

**Comment by talex5** [comment]
Probably it should go on the https://github.com/ocaml-ci/ocaml-ci project.

There's already a pipeline step that finds all the `*.opam` files in the project: https://github.com/ocaml-ci/ocaml-ci/blob/master/service/opam.ml

We could add another step parallel to `build` that does something else with them: https://github.com/ocaml-ci/ocaml-ci/blob/f3279829fbf90868c39995b68cb8dd4b99b66207/service/pipeline.ml#L102

One issue is what to do with the results. The easy way is to treat it as another status context, so you get a red X and a link to the report on the CI service. If instead you want to post it as a comment (as the current bot does) then you'll need to add support for publishing comments to OCurrent's GitHub plugin.

**Comment by AltGr** [comment]
I am not sure this makes sense: most of Camelus code is about retrieving the opam-repository and extracting the part containing the package definitions (diffing to detect what was modified). The linting is just a call to the opam libs.

**Comment by avsm** [comment]
What doesn't make sense about using a CI to coordinate the invocation of Camelus to a specific revision of opam-repository @AltGr? :-)

The intention behind this feature is refactor up some of Camelus such that multiple CI pipelines can use and extend its cool functionality. Since Camelus currently edits a single comment, this minimises email spam to users instead of having multiple bots updating multiple comments on a single PR.

For example:
- The code to diff opam-repository and find out what's changed is very useful for other downstream CI tasks, so it would be useful to make this a concrete build stage. (for example, in datakit-ci there is a hacked together opam-diff container that does this)
- There's the code in Camelus to _update_ a single comment with status, which could in the future be extended to also include other results from the ocaml-ci workflow (e.g. progress on the builds).   I'm keen to use this more in ocurrent, so @talex5's suggestion of making a comment update plugin sounds very good.
- The Github integration would all be taken care of by ocaml-ci, via the App integration

**Comment by AltGr** [comment]
Ah, maybe I misunderstood all the possibilities for use-cases. Camelus is designed to run on an opam-repository, where detecting changed opam files is required — and I had the impression that, for the CI of individual projects, this didn't make sense since what you want is the `*.opam` files directly in the source tree. Of course, I am all in favor of mutualising the comment update and github integration work :)

Camelus does ① linting of opam files, which is just a call to the opam-lib, and ② this diffing + computing installability, which only makes sense on the opam-repository.

But indeed, the CI also runs on opam-repository, so there is no reason not to use a Camelus plugin there :). We should just sync on how the infrastructure is handled (e.g. we are evolving Camelus quickly recently, so would like to be able to test and rollout updates easily). We were also considering the new Github Actions to just run Camelus without extra effort, but a single entry point sounds good.

**Comment by thomasblanc** [comment]
@avsm, I've discussed this privately with Kate, Camelus is about to have more upgrades. Notably, we are thinking about having Camelus propose patches for easy-to-fix problems (e.g. #14906) and extend `camelus_replay auto` to cover updated prs. (and also a few bugfixes like [this one](https://github.com/ocaml/opam-repository/pull/14843#issuecomment-533085824)).

Since we are still adding things to Camelus, it makes sense that it stays on our servers for now. Given your feature wishlist, I'll do my best to keep a clean API :-)

**Comment by avsm** [comment]
That sounds good. I'm not proposing totally decommissioning camelus, but to begin the process of integrating it with current so that we can run it in parallel (not necessarily on the live opam-repo).  For example, it could run camelus against development repositories on `mirage/` to check for upstream opam files becoming uninstallable (which is quite common when opam-repository commits a constraint and we don't feed this back to the original project)

**Comment by kit-ty-kate** [comment]
Closing this old issue in favour of https://github.com/ocurrent/ocurrent/issues/285 and https://github.com/ocurrent/opam-repo-ci/issues/118
